name: All You Need
main: com.crystalcraftmc.allyouneed.Main
version: 0.1.1a

commands:
   ct:
      description: Open a crafting table.
      usage: /ct
      permission: allyouneed.ct
      permission-message: You don't have <permission>
   ender:
      description: Open your ender chest.
      usage: /ender
      permission: allyouneed.ender
      permission-message: You don't have <permission>
   rules:
      description: List the server rules.
      usage: /rules
      permission: allyouneed.rules
      permission-message: You don't have <permission>
   gethelp:
      description: Send private message to all server staff available.
      usage: /gethelp [message]
      permission: allyouneed.rules
      permission-message: You don't have <permission>

permissions:
    allyouneed.*:
        description: Gives access to all All You Need commands
        children:
            allyouneed.ct: true
            allyouneed.ender: true
            allyouneed.rules: true
            allyouneed.gethelp: true
    allyouneed.ct:
        description: Open a crafting table.
        default: op
    allyouneed.ender:
        description: Open your ender chest.
        default: op
    allyouneed.rules:
        description: List the server rules.
        default: not op
    allyouneed.gethelp:
        description: Send private message to all server staff available.
        default: not op